# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f6cad33d701875a5c0f640b978f58c5f501f84db41d94739e4a1b6841361717a125dcf5dfdb00e517d80643bc83f0a666cee5b6a21923098ac8ed3f3810d6a3

test:
  secret_key_base: 74b4b5c500e0692f09c0c18a768ade260f3adf11a7399dfa6f0cca3a15f65f0088239db02cd5248fcbc29e4869eb5fde8f0b58bccec1b359284f65e8bfcee2f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
